apiVersion: apps/v1
kind: Deployment
metadata:
  name: igralci-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igralci
  template:
    metadata:
      labels:
        app: igralci
    spec:
      containers:
        - image: ts4894/igralci:2021-12-18-01-40-26
          name: igralci
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://igralci-db.postgres.database.azure.com:5432/postgres?user=postgresAdmin&sslmode=require
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgresAdmin
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pas-igralci
                  key: password
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: igralci
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: igralci