apiVersion: apps/v1
kind: Deployment
metadata:
  name: igralci-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igralci
  template:
    metadata:
      labels:
        app: igralci
    spec:
      containers:
        - image: ts4894/igralci:2022-01-10-03-58-39
          name: igralci
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              valueFrom:
                secretKeyRef:
                  name: pg-pas-igralci
                  key: password
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: igralci
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: igralci