kumuluzee:
  name: igralci-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://20.120.65.121:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/IgralciMetadataDS
      connection-url: jdbc:postgresql://igralci-db.postgres.database.azure.com:5432/postgres?user=postgresAdmin&sslmode=require
      username: postgresAdmin
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/IgralciMetadataDS
    metrics:
      web-instrumentation:
        - name: igralci-endpoint
          url-pattern: /v1/igralci/*
  rest-client:
    registrations:
      - class: igralci-processing-api
        url: http://20.120.65.121:8082/v1
        read-timeout: 5000
rest-properties:
  maintenance-mode: false
  broken: false
app-properties:
  amazon-rekognition:
    access-key:
    secret-key: